apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosque-clock-api
  namespace: mosque-clock-ai
  labels:
    app: mosque-clock-api
spec:
  replicas: 3                             
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: mosque-clock-api
  template:
    metadata:
      labels:
        app: mosque-clock-api
    spec:
      imagePullSecrets:                 
        - name: regcred
      containers:
        - name: api
          image: mosque-clock-ai:latest   
          imagePullPolicy: Always      
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - secretRef:
                name: mosque-clock-env            
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /openapi.json                       
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /openapi.json
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      restartPolicy: Always
